### ISSUE TITLE
Webpacker support

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/boxcar-generator-archive#101]
- [x] Add `gem 'webpacker', '~> 3.4'`
- [x] `bundle`
- [x] `bundle exec rails webpacker:install`
- [x] `bundle exec rails webpacker:install:react`
- [x] Add `gem "foreman"` to Gemfile in the `:development, :test` group
- [x] Add a `Procfile` with:
```
backend: bundle exec rails server -p 3000
frontend: bin/webpack-dev-server
```
- [x] Create a "hello world" page rendering via a react component, with some SB boilerplate react setup
- [x] Add a system spec that tests the react hello world page
- [x] Update readme instructions
- [x] Remove sass-rails, uglifier, and coffee-rails from the Gemfile
- [x] Remove as much of the asset pipeline as possible (except the ones needed for AA)
- [x] Add `node_modules` to gitignore

**Comment by dkniffin** [comment]
Also part of this should be removing sass-rails, uglifier, and coffee-rails from the gemfile, and removing as much of the asset pipeline as possible. [This PR](https://github.com/smashingboxes/shipmint/pull/8) is a good example of all of what needs to be done.

**Comment by dacur** [comment]
@dkniffin are you linking to a private repo in an OS project???  😅 😛

**Comment by dkniffin** [comment]
@dacur Yes, because I know I'm going to be the one to do this 😛 

Also, we need to add ignore the node_modules folder in rubocop.yml

**Comment by dkniffin** [comment]
Another note: Most of the `app/assets` directory can be removed. If you're using AA, don't delete the AA related files in there.

**Comment by dkniffin** [comment]
I got a good start on this on #121, but stopped after `Add a Procfile with`
