### ISSUE TITLE
Switch wget for curl

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/boxcar-generator-archive#106]
wget isn't installed by default on Mac. We should replace these two lines: https://github.com/smashingboxes/boxcar/blob/8178564069533f02b14385e6a6ca1e1bb3f32d96/lib/boxcar/app_builder.rb#L199-L203 with `curl <url> -o outfile`

**Comment by TylerRockwell** [comment]
I think we can close this since #110 was merged.
