### ISSUE TITLE
Fill in yarn version number

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/boxcar-generator-archive#107]
On [this line](https://github.com/smashingboxes/boxcar/blob/master/templates/travis.yml.erb#L5), we need to replace `version-number` with a real version number

**Comment by woolsox** [comment]
**Note:** in addition to what @dkniffin said, you'll need to add `yarn install` below Line 6 in the `before_install` section: 
[boxcar/templates/travis.yml.erb](url)

**Comment by dkniffin** [comment]
This was resolved by #107. Closing.

FYI @woolsox If you put "fixes #107" (with the appropriate issue number) in a git commit, GH will close the issue for you automatically.
