### ISSUE TITLE
API project precompile assets fails

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/boxcar-generator-archive#27]
When I run `rake assets:precompile` on an API project I get the following error.

```
rake aborted!\nSprockets::FileNotFound: couldn't find file 'jquery' with type 'ap
plication/javascript'\nChecked in these paths: \n
...
```

The `require jquery` and `require jquery_ujs` needs to be remove from our `app/assets/javascript/application.js` file.

**Comment by Ru-T** [comment]
@BrandonMathis open PR to resolve this issue: https://github.com/smashingboxes/boxcar/pull/28
