### ISSUE TITLE
Load factories

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/boxcar-generator-archive#33]
We should add this line to the `spec_helper.rb`:

````
Dir[Rails.root.join("spec/factories/**/*.rb")].each { |f| require f } # factory_girl
````

(if the user chooses to install factorygirl)

**Comment by Ru-T** [comment]
@dkniffin question - I haven't done this before. Instead, I've included spec/support/factory_girl.rb with the following:

`RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods
end`

What does this add?

**Comment by dkniffin** [comment]
I looked into it some more, and it looks like we actually don't need this. What it's supposed to do is include the factories, which I thought wasn't being done, but it is. I was having issues running `create(:user)` or whatever in a `rails c`, which is a separate issue.

**Comment by Ru-T** [comment]
Cool - thanks @dkniffin!
