### ISSUE TITLE
Add activeadmin

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/boxcar-generator-archive#34]
If the user says yes to wanting an api + admin app, activeadmin should be added into the gemfile, and installed, and run:

````
rails generate active_admin:assets
````

**Comment by Ru-T** [comment]
@dkniffin This was originally considered, but the consensus of the team was that ActiveAdmin is not necessarily the admin interface of choice - some folks were leaning towards Administrate. 

Thoughts? Do you think it's worth specifically asking if you want ActiveAdmin?

**Comment by dkniffin** [comment]
Yea, I guess that's true. I think we should ask another y/n for activeadmin.

**Comment by Ru-T** [comment]
Cool. Will add and include a PR.
