### ISSUE TITLE
Use rails ~>5.0.0 instead of 5.0.0

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/boxcar-generator-archive#35]
The generated Gemfile puts `gem :rails, '5.0.0'`. That should read `gem :rails, '~>5.0.0'`

**Comment by Ru-T** [comment]
@dkniffin Thanks for this catch. Fixed here and also had to update config for CodeClimate to get build to pass. 

https://github.com/smashingboxes/boxcar/pull/36

Would love a review - thanks!
