### ISSUE TITLE
Rspec enhancements

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/boxcar-generator-archive#46]
We should configure the following by default

- [x] Put `config.include FactoryGirl::Syntax::Methods` in the `rails_helper.rb`
- [x] Add faker
- [x] Add some [request_helpers](https://github.com/smashingboxes/makers-api/blob/master/spec/support/request_helpers.rb)

**Comment by TylerRockwell** [comment]
@BrandonMathis The `config.include FactoryGirl::Syntax::Methods` is already in `factory_girl.rb` in `spec/support`. Would you prefer it get moved to the rails_helper?

**Comment by TylerRockwell** [comment]
All the suggestions have been implemented. Closing this issue.
