### ISSUE TITLE
Rubocop for Ruby 2.4

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/boxcar-generator-archive#47]
Make the following Rubocop adjustments for ruby 2.4
- [x] Remove `Style/TrailingCommaInArguments:SupportedStyles`
- [x] Remove `Style/TrailingCommaInLiteral:SupportedStyles`
- [x] Set `Metrics/BlockLength` to `Enabled: false` (new thing in rubocop)

**Comment by TylerRockwell** [comment]
These have now been addressed.
