### ISSUE TITLE
Devise token auth should send the token via a user object

### ISSUE THREAD

**Issue by prawl** [smashingboxes/boxcar-generator-archive#76]

**Comment by prawl** [comment]
Todd and I were having a discussion about this.  Todd was having issues and said it felt hacky to pull the devise token from the header in the API request.  I'll investigate in putting the token into the user object.

**Comment by dkniffin** [comment]
I don't think this is possible, for a few reasons:
1. It's how devise_token_auth does it out of the box, so it's going to be hard to change without some serious customization. 
2. The token changes on every request, so how would we handle the case where we're making a request for some other object, like `Posts` or something?

So, I'm going to close this. If we really want to do this, maybe we can revisit
