### ISSUE TITLE
Boxcar should include seeds spec

### ISSUE THREAD

**Issue by prawl** [smashingboxes/boxcar-generator-archive#77]

**Comment by dkniffin** [comment]
In addition to seed specs, we should also settle on a consistent way of doing seeds. On DPT and Stilio, we did [this style](https://github.com/smashingboxes/daimler_plant_tour-api/blob/master/db/seeds.rb#L7-L11). There's also [seedbank](https://github.com/james2m/seedbank), which allows you to modularize your seeds and run them independently.
