### ISSUE TITLE
Devise Token Auth should send consistent error objects

### ISSUE THREAD

**Issue by prawl** [smashingboxes/boxcar-generator-archive#79]

**Comment by prawl** [comment]
When hitting any of the devise token auth endpoints that returns an error the response looks like this ..
{
    "errors": [
        "Invalid login credentials. Please try again."
    ]
}

We'd like it to be more consistent like with it's success responses. 
{
    "status": "success",
    "data": {
        "id": 4,
        "email": "happyday@day.coms",
        "provider": "email",
        "stripe_id": null,
        "uid": "happyday@day.coms",
        "nickname": null,
        "image": null,
        "created_at": "2018-02-26T15:10:55.176Z",
        "updated_at": "2018-02-26T15:10:55.336Z",
        "first_name": null,
        "last_name": null,
        "date_of_birth": null
    }
}

So the ideal response should look like 
{
    "status": "success",
    "data": {},
    "error": {}
}


I looked into this and it's not apparently obvious way to do it without being super hacky.  Will research when I have more time

**Comment by dkniffin** [comment]
It looks like there's not an easy way to change this, so I'm closing this issue.
