### ISSUE TITLE
Enforce double quotes everywhere

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/boxcar-generator-archive#84]
We had some discussion in Slack ([starting here](https://smashingboxes.slack.com/archives/C02FXG77A/p1504796739000468)) a while back about this, and the group consensus was to use double quotes everywhere. This can be enforced with:

```yml
Style/StringLiterals:
  EnforcedStyle: double_quotes
```

For anyone who wants to argue performance, see [this article](https://www.viget.com/articles/just-use-double-quoted-ruby-strings). An attempt was started on this back in [this PR](https://github.com/smashingboxes/boxcar/pull/57), but then I rewrote boxcar and it had tons of conflicts.

**Comment by dacur** [comment]
this is in boxcar on line 121, it just needs to be set to `Enabled: true`
